- apt_repository: repo=ppa:nginx/stable
- apt: pkg=nginx
- group: name=www state=present
- file: path=/var/www/localhost/html state=directory
- user: name=nginx group=www shell=/bin/false home=/var/www/localhost/html
- file: path=/var/www/localhost/html state=directory owner=nginx group=www

- file: path=/var/tmp/nginx state=directory owner=nginx
- service: name=nginx enabled=yes state=started
- name: upload nginx config
  synchronize: >
    src=nginx dest=/etc
    times=no checksum=yes
    recursive=yes delete=yes
    set_remote_user=no rsync_path="sudo rsync"
  notify: restart nginx

- name: fix logrotate nginx reload bug
  replace:
    dest: /etc/logrotate.d/nginx
    regexp: 'invoke-rc.d nginx rotate'
    replace: 'invoke-rc.d nginx reload'
  tags:
    - bugfix
