---
- name: add ubuntu to www-data
  user: name=ubuntu append=yes groups=www-data

- file: path=/var/www owner=ubuntu state=directory
- name: upload ntp.conf
  copy: src=etc/ntp.conf dest=/etc/ntp.conf

- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400
- name: install common packages
  apt: name={{ item }}
  with_items:
    - fail2ban
    - git-core
    - vim
    - screen
    - moreutils
    - autoconf
    - make
    - cmake
    - gcc
    - curl
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - g++

- service: name=fail2ban enabled=yes state=started

- file: path=/home/ubuntu/.ssh owner=ubuntu state=directory
- name: add known ssh hosts
  shell: ssh-keyscan -H bitbucket.org github.com > /home/ubuntu/.ssh/known_hosts
  args:
    creates: /home/ubuntu/.ssh/known_hosts

- name: fix ownership for known hosts
  file: path=/home/ubuntu/.ssh/known_hosts mode=0600 owner=ubuntu
