- apt_repository: repo=ppa:nginx/stable
- apt: pkg=nginx

- service: name=nginx enabled=yes
# - name: upload nginx config
#   synchronize: >
#     src=nginx dest=/etc
#     times=no checksum=yes
#     set_remote_user=no rsync_path="sudo rsync"
#   notify: restart nginx

- name: fix logrotate nginx reload bug
  replace:
    dest: /etc/logrotate.d/nginx
    regexp: 'invoke-rc.d nginx rotate'
    replace: 'invoke-rc.d nginx reload'
  tags:
    - bugfix
